// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relevantz.ProgressPulse.Data.DBContexts;

#nullable disable

namespace Relevantz.ProgressPulse.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228045522_AddTargetCountToGoal")]
    partial class AddTargetCountToGoal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WeeklyLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyLogId");

                    b.ToTable("LogAttachments");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("WeeklyLogId");

                    b.ToTable("LogComments");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogGoalMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("WeeklyLogId");

                    b.ToTable("LogGoalMappings");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPUserManagerMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("UserManagerMappings");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklyLogs");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPGoal", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogAttachment", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", "WeeklyLog")
                        .WithMany("Attachments")
                        .HasForeignKey("WeeklyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyLog");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogComment", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", "WeeklyLog")
                        .WithMany()
                        .HasForeignKey("WeeklyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("WeeklyLog");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPLogGoalMapping", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.PPGoal", "Goal")
                        .WithMany("LogGoalMappings")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", "WeeklyLog")
                        .WithMany("LogGoalMappings")
                        .HasForeignKey("WeeklyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("WeeklyLog");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPUserManagerMapping", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", b =>
                {
                    b.HasOne("Relevantz.ProgressPulse.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPGoal", b =>
                {
                    b.Navigation("LogGoalMappings");
                });

            modelBuilder.Entity("Relevantz.ProgressPulse.Common.Entities.PPWeeklyLog", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("LogGoalMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
