sonar.projectKey=ProgressPulse
sonar.working.directory=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\ProgressPulse\\Backend
sonar.pullrequest.cache.basepath=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api
sonar.sources=\
"D:\\ProgressPulse\\Backend\\.config\\dotnet-tools.json",\
"D:\\ProgressPulse\\Backend\\ollama\\entrypoint.sh",\
"D:\\ProgressPulse\\Backend\\ai-service\\fastapi\\Dockerfile",\
"D:\\ProgressPulse\\Backend\\ai-service\\fastapi\\main.py",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api.Tests\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api.Tests\\obj\\Relevantz.ProgressPulse.Api.Tests.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common.Tests\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common.Tests\\obj\\Relevantz.ProgressPulse.Common.Tests.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\obj\\Relevantz.ProgressPulse.Core.Tests.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data.Tests\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data.Tests\\obj\\Relevantz.ProgressPulse.Data.Tests.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\appsettings.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.runtimeconfig.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.staticwebassets.runtime.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Core.Tests.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core.Tests\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Core.Tests.runtimeconfig.json",\
"D:\\ProgressPulse\\Backend\\.env",\
"D:\\ProgressPulse\\Backend\\docker-compose.yml",\
"D:\\ProgressPulse\\Backend\\Dockerfile",\
"D:\\ProgressPulse\\Backend\\global.json"

23E00C54-8DCA-43B5-A960-79F13554438E.sonar.projectKey=ProgressPulse:23E00C54-8DCA-43B5-A960-79F13554438E
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.projectName=Relevantz.ProgressPulse.Common
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.projectBaseDir=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.sourceEncoding=utf-8
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.tests=
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.sources=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Class1.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\AddCommentRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\AssignGoalRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\CreateGoalRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\CreateWeeklyLogRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\DigestRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\GoalSummaryRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\LoginRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\ManagerLogFilterRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\ProgressRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\UpdateGoalRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Request\\UpdateProgressRequest.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\AppraisalReportResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\AttachmentResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\EmployeeListResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\EmployeeSummaryResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\GoalDetailResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\GoalProgressResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\GoalResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\GoalTagResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\LogCommentResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\LoginResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\ManagerDashboardResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\ManagerLogResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\ProfileResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\QuarterlyActivityResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\WeeklyDigestResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\DTOs\\Response\\WeeklyLogResponse.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPGoal.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPLogAttachment.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPLogComment.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPLogGoalMapping.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPUserManagerMapping.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\PPWeeklyLog.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Entities\\User.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\AddCommentRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\AssignGoalRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\CreateGoalRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\CreateWeeklyLogRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\LoginRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\ManagerLogFilterRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\UpdateGoalRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\Validators\\UpdateProgressRequestValidator.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\obj\\Relevantz.ProgressPulse.Common.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Common.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Common\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Common.sourcelink.json"

23E00C54-8DCA-43B5-A960-79F13554438E.sonar.cs.analyzer.projectOutPaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\0"
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.cs.roslyn.reportFilePaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\0\\Issues.json"
23E00C54-8DCA-43B5-A960-79F13554438E.sonar.cs.scanner.telemetry=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\0\\Telemetry.json"

23E00C54-8DCA-43B5-A960-79F13554438E.sonar.working.directory=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\.sonar\\mod0
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.projectKey=ProgressPulse:51D3989C-EC9B-46F6-AFEC-278013EAAFAB
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.projectName=Relevantz.ProgressPulse.Data
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.projectBaseDir=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.sourceEncoding=utf-8
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.tests=
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.sources=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\obj\\Relevantz.ProgressPulse.Data.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Data.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Data.runtimeconfig.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Data.sourcelink.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Class1.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\DBContexts\\AppDbContext.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\IRepository\\IGoalRepository.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\IRepository\\IWeeklyLogRepository.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260227143944_InitialMigrate.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260227143944_InitialMigrate.Designer.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260228045522_AddTargetCountToGoal.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260228045522_AddTargetCountToGoal.Designer.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260228051900_FixCommentForeignKey.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260228051900_FixCommentForeignKey.Designer.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260303072029_AddManagerFieldsToGoal.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\20260303072029_AddManagerFieldsToGoal.Designer.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Migrations\\AppDbContextModelSnapshot.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Repository\\GoalRepository.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Data\\Repository\\WeeklyLogRepository.cs"

51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.cs.analyzer.projectOutPaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\1"
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.cs.roslyn.reportFilePaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\1\\Issues.json"
51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.cs.scanner.telemetry=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\1\\Telemetry.json"

51D3989C-EC9B-46F6-AFEC-278013EAAFAB.sonar.working.directory=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\.sonar\\mod1
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.projectKey=ProgressPulse:91D204B7-8624-40B7-AA05-2A0B74B5C1BD
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.projectName=Relevantz.ProgressPulse.Core
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.projectBaseDir=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.sourceEncoding=utf-8
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.tests=
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.sources=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\obj\\Relevantz.ProgressPulse.Core.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Core.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Core.sourcelink.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Class1.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\IAttachmentService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\IAuthService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\ICommentService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\IGoalService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\IManagerService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\IService\\IWeeklyLogService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\AttachmentService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\AuthService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\CommentService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\GoalService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\ManagerService.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Core\\Service\\WeeklyLogService.cs"

91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.cs.analyzer.projectOutPaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\2"
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.cs.roslyn.reportFilePaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\2\\Issues.json"
91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.cs.scanner.telemetry=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\2\\Telemetry.json"

91D204B7-8624-40B7-AA05-2A0B74B5C1BD.sonar.working.directory=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\.sonar\\mod2
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.projectKey=ProgressPulse:E139AE92-2103-443B-892C-8FE9CD57FE72
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.projectName=Relevantz.ProgressPulse.Api
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.projectBaseDir=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.sourceEncoding=utf-8
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.tests=
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.sources=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\appsettings.Development.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\appsettings.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\project.assets.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Relevantz.ProgressPulse.Api.csproj.nuget.dgspec.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Properties\\launchSettings.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\bin\\Debug\\net8.0\\appsettings.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.deps.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.runtimeconfig.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\bin\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.staticwebassets.runtime.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.sourcelink.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\staticwebassets.development.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\staticwebassets.pack.json",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\AIController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\AttachmentController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\AuthController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\GoalController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\ManagerController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\ManagerGoalController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Controllers\\WeeklyLogController.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Helpers\\DateExtensions.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Program.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\WeatherForecast.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.GlobalUsings.g.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.AssemblyInfo.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\obj\\Debug\\net8.0\\Relevantz.ProgressPulse.Api.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\wwwroot\\uploads\\b3529164-477f-4d3a-a944-f5c2fdfc4ee3.pdf",\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\Relevantz.ProgressPulse.Api.http"

E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.cs.analyzer.projectOutPaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\3"
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.cs.roslyn.reportFilePaths=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\3\\Issues.json"
E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.cs.scanner.telemetry=\
"D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\3\\Telemetry.json"

E139AE92-2103-443B-892C-8FE9CD57FE72.sonar.working.directory=D:\\ProgressPulse\\Backend\\Relevantz.ProgressPulse.Api\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=23E00C54-8DCA-43B5-A960-79F13554438E,51D3989C-EC9B-46F6-AFEC-278013EAAFAB,91D204B7-8624-40B7-AA05-2A0B74B5C1BD,E139AE92-2103-443B-892C-8FE9CD57FE72

